import type { BankAccount } from "@/lib/settings";

// FR22: VietQR (NAPAS) quick-link image. No API key; the image is generated by img.vietqr.io.

/** Transfer content must be ASCII letters/digits, max 25 chars (e.g. `TUA0012`, `UH0005`). */
export function transferContent(code: string): string {
  return code
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/đ/gi, "d")
    .replace(/[^A-Za-z0-9]/g, "")
    .toUpperCase()
    .slice(0, 25);
}

export function isBankConfigured(bank: BankAccount): boolean {
  return Boolean(bank.bankId && bank.accountNo && bank.accountName);
}

export function vietQrUrl(bank: BankAccount, amount: number, content: string): string {
  const params = new URLSearchParams({
    amount: String(Math.round(amount)),
    addInfo: transferContent(content),
    accountName: bank.accountName,
  });
  const path = `${encodeURIComponent(bank.bankId)}-${encodeURIComponent(bank.accountNo)}-compact2.png`;
  return `https://img.vietqr.io/image/${path}?${params}`;
}
