import type { BankAccount } from "@/lib/settings";

// FR22: VietQR (NAPAS) quick-link image. No API key; the image is generated by img.vietqr.io.

/** Transfer content: ASCII letters, digits and single spaces, max 25 chars (e.g. `TUA0012`, `DONATION UH0005`). */
export function transferContent(text: string): string {
  return text
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/đ/gi, "d")
    .replace(/[^A-Za-z0-9 ]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .toUpperCase()
    .slice(0, 25);
}

/**
 * FR08/BR04: donations start with DONATION so they stand apart from TUA orders even when the fund
 * and sales accounts are the same; the code after it lets staff match the transfer to the donation.
 */
export function donationContent(code: string): string {
  return transferContent(`DONATION ${code}`);
}

export function isBankConfigured(bank: BankAccount): boolean {
  return Boolean(bank.bankId && bank.accountNo && bank.accountName);
}

export function vietQrUrl(bank: BankAccount, amount: number, content: string): string {
  const params = new URLSearchParams({
    amount: String(Math.round(amount)),
    addInfo: transferContent(content),
    accountName: bank.accountName,
  });
  const path = `${encodeURIComponent(bank.bankId)}-${encodeURIComponent(bank.accountNo)}-compact2.png`;
  return `https://img.vietqr.io/image/${path}?${params}`;
}
