import "server-only";
import { MAX_IMAGES, assetIdsIn, printSizePx } from "@/lib/design/types";
import type { Settings } from "@/lib/settings";
import { createServiceClient } from "@/lib/supabase/server";

// Canvas exports for web orders (NFR05). The browser renders the PNGs; the server
// checks and stores them in the private `designs` bucket, one file per request so
// each request stays under the hosting body limit. Files live under
// `web/<uploadId>/` until createOrder links them to the order.
// Print files are generated by our canvas: only exact print-size PNGs and our own JSON are
// accepted. Buyer photos (BR01) are referenced by asset id inside the JSON, never embedded.

export const DESIGNS_BUCKET = "designs";
export const MAX_AREA_BYTES = 4 * 1024 * 1024;
const MAX_PREVIEW_BYTES = 1024 * 1024;
const MAX_JSON_BYTES = 4 * 1024 * 1024;
const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

export type UploadKind = "area" | "preview" | "json";

/** Width and height from a PNG header, or null if the bytes are not a PNG. */
export function readPngSize(buf: Uint8Array): { width: number; height: number } | null {
  if (buf.length < 24 || PNG_SIGNATURE.some((b, i) => buf[i] !== b)) return null;
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  return { width: view.getUint32(16), height: view.getUint32(20) };
}

const folder = (uploadId: string) => `web/${uploadId}`;

/** Validates one uploaded design file and stores it. Returns a Vietnamese error or null. */
export async function saveDesignFile(
  input: { uploadId: string; kind: UploadKind; area?: string; file: File },
  settings: Pick<Settings, "print_areas" | "export_dpi">,
): Promise<string | null> {
  const { uploadId, kind, file } = input;
  const bytes = new Uint8Array(await file.arrayBuffer());
  let path: string;
  let contentType = "image/png";

  if (kind === "area") {
    const area = settings.print_areas.find((a) => a.key === input.area);
    if (!area) return "Vùng in không hợp lệ";
    if (bytes.length > MAX_AREA_BYTES) return `File in vùng "${area.label}" quá lớn`;
    const size = readPngSize(bytes);
    const expected = printSizePx(area, settings.export_dpi);
    if (!size || size.width !== expected.widthPx || size.height !== expected.heightPx) {
      return `File in vùng "${area.label}" không đúng kích thước ${expected.widthPx}×${expected.heightPx}px`;
    }
    path = `${folder(uploadId)}/${area.key}.png`;
  } else if (kind === "preview") {
    const size = readPngSize(bytes);
    if (!size || bytes.length > MAX_PREVIEW_BYTES || size.width > 2000 || size.height > 1000) {
      return "Ảnh xem trước không hợp lệ";
    }
    path = `${folder(uploadId)}/preview.png`;
  } else {
    if (bytes.length > MAX_JSON_BYTES) return "Dữ liệu thiết kế quá lớn";
    try {
      const parsed: unknown = JSON.parse(new TextDecoder().decode(bytes));
      const keys = settings.print_areas.map((a) => a.key);
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed) || Object.keys(parsed).some((k) => !keys.includes(k))) {
        return "Dữ liệu thiết kế không hợp lệ";
      }
    } catch {
      return "Dữ liệu thiết kế không hợp lệ";
    }
    path = `${folder(uploadId)}/design.json`;
    contentType = "application/json";
  }

  const { error } = await createServiceClient()
    .storage.from(DESIGNS_BUCKET)
    .upload(path, bytes, { contentType, upsert: true });
  if (error) {
    console.error("[designs] upload failed", path, error.message);
    return "Không tải được thiết kế lên. Vui lòng thử lại.";
  }
  return null;
}

export type UploadedDesign = {
  source: "CANVAS";
  /** `assets`: buyer photos the design uses (design_assets ids), for staff review (FR29). */
  canvas_json: { file: string; assets: string[] };
  preview_url: string | null;
  files: { area: string; file_path: string; width_px: number; height_px: number }[];
};

/** Reads what was uploaded under `uploadId` and shapes it for the create_order RPC. */
export async function collectUploadedDesign(
  uploadId: string,
  settings: Pick<Settings, "print_areas" | "export_dpi">,
): Promise<UploadedDesign | null> {
  const { data, error } = await createServiceClient().storage.from(DESIGNS_BUCKET).list(folder(uploadId));
  if (error) throw new Error(`Không đọc được thiết kế: ${error.message}`);
  const names = new Set((data ?? []).map((f) => f.name));
  if (!names.has("design.json")) return null;

  const files = settings.print_areas
    .filter((a) => names.has(`${a.key}.png`))
    .map((a) => {
      const { widthPx, heightPx } = printSizePx(a, settings.export_dpi);
      return { area: a.key, file_path: `${folder(uploadId)}/${a.key}.png`, width_px: widthPx, height_px: heightPx };
    });
  if (!files.length) return null;

  const jsonPath = `${folder(uploadId)}/design.json`;
  const { data: json, error: jsonError } = await createServiceClient().storage.from(DESIGNS_BUCKET).download(jsonPath);
  if (jsonError || !json) throw new Error(`Không đọc được design.json: ${jsonError?.message}`);
  const assets = assetIdsIn(JSON.parse(await json.text()));
  if (assets.length > MAX_IMAGES) return null;

  return {
    source: "CANVAS",
    canvas_json: { file: jsonPath, assets },
    preview_url: names.has("preview.png") ? `${folder(uploadId)}/preview.png` : null,
    files,
  };
}
